CrowdStrike/csproto

- .golangci.yml
- Makefile
- cmd/protoc-gen-fastmarshal/funcs.go
- cmd/protoc-gen-fastmarshal/templates/permessage.go.tmpl
- cmd/protoc-gen-fastmarshal/templates/singlefile.go.tmpl
- example/proto2/gogo/gogo_proto2_example.pb.fm.go
- example/proto2/googlev1/googlev1_proto2_example.pb.fm.go
- example/proto2/googlev2/googlev2_proto2_example.pb.fm.go
- example/proto2_gogo_test.go
- example/proto2_googlev1_test.go
- example/proto2_googlev2_test.go
- updated codegen templates to emit checks that all required fields are assigned during unmarshal
- added associated tests
- regenerated all examples
Resolves #12
This PR also includes tweaks to the linter setup (see #2) so that we also lint the nested module in `example/` and skip linting test files
> fix: Unmarshal should fail if required fields are missing

- .github/workflows/release.yml
- .gitignore
- .goreleaser.yaml
- Makefile
add Goreleaser config and GH action
add new `snapshot` Make target
~Note: this does not include publishing artifacts yet.  wanted to get the basics working and up for review first.~
The CI build now triggers when a release is published (stable and pre-release) and builds and uploads archives (tarball for Linux and Mac and zip for Windows) with pre-built binaries and attached them to the release.
To test, I forked the repo into my personal GH, merged this branch, then created several releases with a minor change between each.
> feat: integrate Goreleaser for building binaries

- json.go
- json_test.go
adds new `MarshalJSON()` function to generated formatted JSON output for a message
Resolves #9
> feat(json): add runtime-agnostic ability to write messages to JSON

- README.md
- extensions.go
add new `ClearExtension()` API for clearing/removing a proto2 extension field in a runtime-agnostic manner
> feat: add ClearExtension() API

- decoder.go
- json.go
removed never-true comparisons against max int values
added `//nolint` to suppress warnings about references to `github.com/golang/protobuf`
This will also resolve the build failure in #41.
> fix: resolve new linter warnings reported after upgrading golangci-lint to v1.46

- extensions.go
The logic was missing early returns in each case of the `select` so it was falling through to the panic at the end.  Also corrected an inverted check in the case for `MessageTypeGoogleV1`.
> fix: address incorrect panic in ClearExtension()

- cmd/protoc-gen-fastmarshal/templates/fieldsnippets.tmpl
- example/permessage/gogo/gogo_permessage_example_repeatallthethings.pb.fm.go
- example/permessage/gogo/gogo_permessage_example_testevent.pb.fm.go
- example/permessage/googlev1/googlev1_permessage_example_repeatallthethings.pb.fm.go
- example/permessage/googlev1/googlev1_permessage_example_testevent.pb.fm.go
- example/permessage/googlev2/googlev2_permessage_example_repeatallthethings.pb.fm.go
- example/permessage/googlev2/googlev2_permessage_example_testevent.pb.fm.go
- example/proto2/gogo/gogo_proto2_example.pb.fm.go
- example/proto2/googlev1/googlev1_proto2_example.pb.fm.go
- example/proto2/googlev2/googlev2_proto2_example.pb.fm.go
- example/proto3/gogo/gogo_proto3_example.pb.fm.go
- example/proto3/googlev1/googlev1_proto3_example.pb.fm.go
- example/proto3/googlev2/googlev2_proto3_example.pb.fm.go
Updated code generation templates to not ignore zero-length `string` and `[]byte` fields when calculating the encoded message size
Before this change, messages that had an empty string (or empty `[]byte`) in a repeated field would generate a panic in the generated `MarshalTo(dest []byte) error` method for the message because the calculated size did not include the tag and length of 0 for those values.
> fix(codegen): correct size calculation for messages with repeated string or bytes fields

- README.md
- cmd/protoc-gen-fastmarshal/templates/fieldsnippets.tmpl
- cmd/protoc-gen-fastmarshal/templates/permessage.go.tmpl
- cmd/protoc-gen-fastmarshal/templates/singlefile.go.tmpl
- example/permessage/gogo/gogo_permessage_example_allthemaps.pb.fm.go
- example/permessage/gogo/gogo_permessage_example_allthethings.pb.fm.go
- example/permessage/gogo/gogo_permessage_example_embeddedevent.pb.fm.go
- example/permessage/gogo/gogo_permessage_example_nestedmsg.pb.fm.go
- example/permessage/gogo/gogo_permessage_example_repeatallthethings.pb.fm.go
- example/permessage/gogo/gogo_permessage_example_testevent.pb.fm.go
- example/permessage/googlev1/googlev1_permessage_example_allthemaps.pb.fm.go
- example/permessage/googlev1/googlev1_permessage_example_allthethings.pb.fm.go
- example/permessage/googlev1/googlev1_permessage_example_embeddedevent.pb.fm.go
- example/permessage/googlev1/googlev1_permessage_example_nestedmsg.pb.fm.go
- example/permessage/googlev1/googlev1_permessage_example_repeatallthethings.pb.fm.go
- example/permessage/googlev1/googlev1_permessage_example_testevent.pb.fm.go
- example/permessage/googlev2/googlev2_permessage_example_allthemaps.pb.fm.go
- example/permessage/googlev2/googlev2_permessage_example_allthethings.pb.fm.go
- example/permessage/googlev2/googlev2_permessage_example_embeddedevent.pb.fm.go
- example/permessage/googlev2/googlev2_permessage_example_nestedmsg.pb.fm.go
- example/permessage/googlev2/googlev2_permessage_example_repeatallthethings.pb.fm.go
- example/permessage/googlev2/googlev2_permessage_example_testevent.pb.fm.go
- example/proto2/gogo/gogo_proto2_example.pb.fm.go
- example/proto2/googlev1/googlev1_proto2_example.pb.fm.go
- example/proto2/googlev2/googlev2_proto2_example.pb.fm.go
- example/proto3/gogo/gogo_proto3_example.pb.fm.go
- example/proto3/googlev1/googlev1_proto3_example.pb.fm.go
- example/proto3/googlev2/googlev2_proto3_example.pb.fm.go
add logic in generated code to cache calculated size to avoid double work across `Size()` and `MarshalTo()`
modify codegen templates to skip zero-valued fields when sizing and marshaling proto3 messages
> fix: address perf and compatibility issues

- cmd/protoc-gen-fastmarshal/templates/fieldsnippets.tmpl
fixed copy/paste bug in the codegen template
float/double fields should use `DecodeFloat*` instead of `DecodeFixed*`
fixes #54
> fix(codegen): correct invalid generated code for float or double oneof fields

- example/proto2_gogo_test.go
- example/proto2_googlev1_test.go
- example/proto2_googlev2_test.go
- example/proto3_gogo_test.go
- example/proto3_googlev1_test.go
- example/proto3_googlev2_test.go
- marshal_text.go
adds `MarshalText(interface{}) (string, error)` and associated unit tests
> feat: add new MarshalText() API

- cmd/protoc-gen-fastmarshal/templates/fieldsnippets.tmpl
Message fields are length-delimited binary but the size calculation was not including the field tag and length, resulting in panics when writing past the end of the allocated buffer inside of `csproto.Marshal()`.
This PR updates the code generation templates for `protoc-gen-fastmarshal` to correct the calculation.
> fix(protoc-gen-fastmarshal): incorrect size calculation for message oneof fields

- encoder.go
- example/proto2_gogo_test.go
- example/proto2_googlev1_test.go
- example/proto2_googlev2_test.go
- example/proto3_gogo_test.go
- example/proto3_googlev1_test.go
- example/proto3_googlev2_test.go
- json.go
- add exported functions for `EncodeFixed(32|64)` for completeness/consistency
- add API for JSON unmarshaling with associated tests
> feat: add missing proto APIs

- .gitignore
- clone.go
- example/proto2_gogo_test.go
- example/proto2_googlev1_test.go
- example/proto2_googlev2_test.go
- example/proto3_gogo_test.go
- example/proto3_googlev1_test.go
- example/proto3_googlev2_test.go
- add new `csproto.Clone()` function and associated tests
- add `go.work*` to `.gitignore`
> feat: add Clone() function

- decoder.go
- decoder_test.go
Adds a bounds check to `Decoder.DecodeBytes()` to return `io.ErrUnexpectedEOF` instead of panicking if the encoded data is shorter than the encoded length
> fix: avoid panic when decoding an invalid length-delimited field

- extensions.go
adds a new `ExtensionFieldNumber(any)` API that returns the field tag associated with a proto2 extension field descriptor
> feat: add ExtensionFieldNumber() function

- decoder.go
- decoder_test.go
- example/proto2_gogo_test.go
- example/proto2_googlev1_test.go
- example/proto2_googlev2_test.go
- extensions.go
This PR adds bounds checks to all paths in `Decoder` to avoid panics when attempting to decode invalid/corrupt Protobuf messages.  The changes had a minimal impact on benchmarks, so the general safety is a net win.
I also addressed a new linter warning that was introduced in v0.15.0 and added unit tests for the `ExtensionFieldNumber(any) int` function
> Avoid panics when decoding invalid messages

- decoder.go
- decoder_test.go
updated `Decoder.DecodeBytes()` to return an error if the decoded byte length is <0
> fix(decoder): address panic when decoding invalid/corrupt messages

- .github/workflows/go.yml
- .goreleaser.yaml
- Makefile
- cmd/protodump/main.go
- cmd/protodump/tagpath.go
- cmd/protodump/tagpath_test.go
- decoder.go
- decoder_test.go
This PR addresses a panic when calling `.String()` on a decoded message struct when the encoded message contained unknown/unrecognized data that is not a valid encoded field value.  The specific case that exposed this was an internal message that had 6 extra zero bytes after a `google.protobuf.Timestamp` field.  Those extra bytes got copied to the `unknownFields` field on the Go struct.
Google's runtime implementation returns an error for the same data so the "fix" was to update `Decoder` to also return an error.  This is potentially a breaking change because the prior code did not return an error.
While troubleshooting this issue, I also wrote a new `protodump` CLI that can decode a binary message and output basic tag/wire type info without depending on the Protobuf file descriptor.  I …
> Fix panic after decoding msg with invalid unknown fields

- example/proto2_gogo_test.go
- example/proto2_googlev1_test.go
- example/proto2_googlev2_test.go
- extensions.go
The Google V2 `RangeExtensions` API takes a callback that returns `bool` instead of `error` and we were returning `err != nil`, which returns `false` if there was no error and exits the enumeration.
This PR fixes the logic and adds unit tests for all three supported runtimes.
> fix: RangeExtensions doesn't enumerate all items for Google V2

- cmd/protoc-gen-fastmarshal/funcs.go
- cmd/protoc-gen-fastmarshal/generator.go
- cmd/protoc-gen-fastmarshal/templates/permessage.go.tmpl
- cmd/protoc-gen-fastmarshal/templates/singlefile.go.tmpl
- example/permessage/gogo/gogo_permessage_example_testevent.pb.fm.go
- example/proto2/gogo/gogo_proto2_example.pb.fm.go
- example/proto2/googlev1/googlev1_proto2_example.pb.fm.go
- example/proto2/googlev2/googlev2_proto2_example.pb.fm.go
- example/proto3/gogo/gogo_proto3_example.pb.fm.go
- example/proto3/googlev1/googlev1_proto3_example.pb.fm.go
- example/proto3/googlev2/googlev2_proto3_example.pb.fm.go
Updates the logic that generates additional imports to extract the `go_package` option from the parent .proto file and include the explicit package name, if present update the codegen templates to use the package alias if set
Fixes #121
> fix(protoc-gen-fastmarshal): generated code should respect Go package aliases from 'option go_package'

- decoder.go
- decoder_test.go
add new `Seek()` method (satisfying `io.Seeker`) to `Decoder` with associated tests
also add `Mode()` to expose the read mode (fast vs safe) to consumers
> feat: add `Seek()` method to `Decoder`

- helpers_generic.go
This PR loosens the generic type constraint on `PointerTo[T]()` to replace `int32` with `~int32` so that we include generated enum types and adds additional clarifying comments.
> feat: expand `PointerTo[T]()` function to support proto enums

- .golangci.yml
- decoder.go
- decoder_test.go
- example/proto2_gogo_test.go
- example/proto2_googlev1_test.go
- example/proto2_googlev2_test.go
- example/proto3_gogo_test.go
- example/proto3_googlev1_test.go
- example/proto3_googlev2_test.go
- lazyproto/decode_test.go
- prototest/parse_annotated_hex.go
This PR resolves a panic when trying to decode a corrupted message, specifically one where the encoded length of a string field is >2GB.
I also added a new `ParseAnnotatedHex()` function in a new `prototest` package.  This function can be used to convert a string containing a "commented" hexadecimal representation of an encoded Protobuf message into binary, which is useful for managing test data in a more human-readable form.  See the godoc comments on the function for more details.
Finally, I updated `.golangci.yml` to resolve some config deprecations, which led to having to update some test code that was now generating linter warnings.
Fixes #158
> fix: Resolve panic in `Decoder.Skip()` with corrupt message
